name: lend
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Navbar
  persistent_bottom_nav_bar_v2: ^5.3.1

  # Firebase SDKs
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.5
  cloud_functions: ^5.3.3
  firebase_messaging: ^15.2.10
  firebase_remote_config: ^5.5.0

  # Firebase Social Auth
  google_sign_in: ^6.3.0
  sign_in_with_apple: ^6.1.4
  flutter_facebook_auth: ^7.1.1

  # Google Maps
  google_maps_flutter: ^2.17.0
  geocoding: ^3.0.0
  geolocator: ^10.0.0
  google_places_flutter: ^2.1.0
  geoflutterfire_plus: ^0.0.24

  # State Management
  get: ^4.7.2
  get_storage: ^2.1.1

  # Utilities
  intl: ^0.20.2
  logger: ^2.5.0
  crypto: ^3.0.6
  flutter_dotenv: ^5.2.1
  permission_handler: ^12.0.1
  gal: ^2.3.1
  image_picker: ^1.2.2
  dart_either: ^2.0.0
  timeago: ^3.7.1
  pluralize: ^0.0.8
  dio: ^5.9.0
  flutter_pdfview: ^1.4.3
  path_provider: ^2.1.5
  local_auth: ^3.0.1
  app_settings: ^7.0.0
  app_links: ^7.0.0
  infinite_scroll_pagination: ^5.1.1

  # UI Components
  mobile_scanner: ^7.2.0
  calendar_date_picker2: ^1.1.9
  sliding_up_panel: ^2.0.0+1
  flutter_carousel_widget: ^3.1.0
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.8.0
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.17
  dotted_border: ^2.1.0
  modal_bottom_sheet: ^3.0.0
  card_swiper: ^3.0.1
  qr_flutter: ^4.1.0
  step_progress: ^2.5.2
  pull_down_button: ^0.10.2
  url_launcher: ^6.3.2
  share_plus: ^12.0.2
  duration_picker: ^1.2.0
  flutter_credit_card: ^4.1.0

  # KYC
  didit_sdk: ^3.7.1

  # Search Service
  algoliasearch: ^1.49.1
  sealed_countries: ^3.1.0

  # Secure Storage
  flutter_secure_storage: ^10.3.1
  local_auth_android: ^2.0.8
  local_auth_darwin: ^2.0.3
  file_picker: ^11.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/generated/app_icon.png"
  image_path_android: "assets/generated/android_launcher_logo.png"
  remove_alpha_ios: true
  background_color_ios: "#ff6b00"

flutter:
  uses-material-design: true

  assets:
    - envs/
    - assets/generated/
    - assets/images/
    - assets/images/payment/
    - assets/svg/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Bold.ttf
        - asset: fonts/Inter-Medium.ttf
          weight: 400
