import 'package:flutter/widgets.dart';
import 'package:font_awesome_flutter/font_awesome_flutter.dart';

IconData categoryIconFromKey(String? key) {
  return _categoryIconRegistry[_normalizeCategoryIconKey(key)] ??
      FontAwesomeIcons.box;
}

String _normalizeCategoryIconKey(String? key) {
  return key?.trim().replaceAll(RegExp(r'[\s_-]+'), '').toLowerCase() ?? '';
}

const Map<String, IconData> _categoryIconRegistry = {
  'camera': FontAwesomeIcons.camera,
  'cameras': FontAwesomeIcons.camera,
  'car': FontAwesomeIcons.car,
  'cars': FontAwesomeIcons.car,
  'motorcycles': FontAwesomeIcons.motorcycle,
  'vans': FontAwesomeIcons.vanShuttle,
  'trucks': FontAwesomeIcons.truck,
  'vehicle': FontAwesomeIcons.car,
  'vehicles': FontAwesomeIcons.car,
  'powertools': FontAwesomeIcons.screwdriverWrench,
  'handtools': FontAwesomeIcons.screwdriverWrench,
  'gardentools': FontAwesomeIcons.seedling,
  'ladders': FontAwesomeIcons.screwdriverWrench,
  'cleaningequipment': FontAwesomeIcons.broom,
  'tools': FontAwesomeIcons.screwdriverWrench,
  'toolsequipment': FontAwesomeIcons.screwdriverWrench,
  'screwdriverwrench': FontAwesomeIcons.screwdriverWrench,
  'space': FontAwesomeIcons.warehouse,
  'spaces': FontAwesomeIcons.warehouse,
  'stayspaces': FontAwesomeIcons.house,
  'stays': FontAwesomeIcons.house,
  'parkingspaces': FontAwesomeIcons.squareParking,
  'storagespaces': FontAwesomeIcons.warehouse,
  'eventvenues': FontAwesomeIcons.champagneGlasses,
  'warehouse': FontAwesomeIcons.warehouse,
  'outdoor': FontAwesomeIcons.personHiking,
  'outdoorgear': FontAwesomeIcons.personHiking,
  'outdoorgears': FontAwesomeIcons.personHiking,
  'campinggear': FontAwesomeIcons.campground,
  'hikinggear': FontAwesomeIcons.personHiking,
  'sportsequipment': FontAwesomeIcons.futbol,
  'bikesscooters': FontAwesomeIcons.bicycle,
  'watersports': FontAwesomeIcons.water,
  'personhiking': FontAwesomeIcons.personHiking,
  'electronics': FontAwesomeIcons.computer,
  'phonestablets': FontAwesomeIcons.mobileScreenButton,
  'computerslaptops': FontAwesomeIcons.computer,
  'audioequipment': FontAwesomeIcons.headphones,
  'gamingconsoles': FontAwesomeIcons.gamepad,
  'computer': FontAwesomeIcons.computer,
  'drone': FontAwesomeIcons.helicopter,
  'drones': FontAwesomeIcons.helicopter,
  'helicopter': FontAwesomeIcons.helicopter,
  'hobbies': FontAwesomeIcons.palette,
  'musicalinstruments': FontAwesomeIcons.guitar,
  'artscrafts': FontAwesomeIcons.palette,
  'boardgames': FontAwesomeIcons.dice,
  'collectibles': FontAwesomeIcons.boxOpen,
  'fitnessgear': FontAwesomeIcons.dumbbell,
  'party': FontAwesomeIcons.champagneGlasses,
  'partyevents': FontAwesomeIcons.champagneGlasses,
  'partysupplies': FontAwesomeIcons.champagneGlasses,
  'tableschairs': FontAwesomeIcons.chair,
  'soundlighting': FontAwesomeIcons.volumeHigh,
  'photoboothequipment': FontAwesomeIcons.cameraRetro,
  'costumes': FontAwesomeIcons.masksTheater,
  'champagneglasses': FontAwesomeIcons.champagneGlasses,
  'lens': FontAwesomeIcons.circleDot,
  'lenses': FontAwesomeIcons.circleDot,
  'circledot': FontAwesomeIcons.circleDot,
  'fashion': FontAwesomeIcons.shirt,
  'clothes': FontAwesomeIcons.shirt,
  'clothing': FontAwesomeIcons.shirt,
  'shoes': FontAwesomeIcons.shoePrints,
  'bagsaccessories': FontAwesomeIcons.bagShopping,
  'jewelryaccessories': FontAwesomeIcons.gem,
  'shirt': FontAwesomeIcons.shirt,
  'tshirt': FontAwesomeIcons.shirt,
  'bookslearning': FontAwesomeIcons.bookOpen,
  'books': FontAwesomeIcons.book,
  'textbooks': FontAwesomeIcons.bookOpen,
  'learningmaterials': FontAwesomeIcons.graduationCap,
  'schoolsupplies': FontAwesomeIcons.pencil,
  'house': FontAwesomeIcons.house,
  'home': FontAwesomeIcons.house,
  'others': FontAwesomeIcons.box,
  'homeappliances': FontAwesomeIcons.house,
  'babykids': FontAwesomeIcons.baby,
  'petsupplies': FontAwesomeIcons.paw,
  'miscellaneous': FontAwesomeIcons.box,
  'services': FontAwesomeIcons.peopleArrows,
};
